---
- debug: 
    msg: Configuring packages on host {{ ansible_host }}

- name: Package Installation - shell utils (CentOS)
  when: ansible_facts["distribution"] == "CentOS"
  package:
    name: ['zsh', 'tmux', 'python3', 'git']
    state: present

- name: Package Installation - shell utils (Ubuntu/Fedora)
  when: (ansible_facts["distribution"] == "Ubuntu") or
        (ansible_facts["distribution"] == "Fedora")
  package:
    name: ['zsh', 'tmux', 'python3-pip', 'git', 'acl']
    state: present

- include_role:
    name: geerlingguy.pip

- name: Package Installation - python
  pip:
    name: 'powerline-status'

- include_role:
    name: geerlingguy.docker
  vars:
    docker_http_proxy: "{{ proxy }}"
    docker_https_proxy: "{{ proxy }}"
    docker_no_proxy: "{{ no_proxy }}"
    docker_users:
      - "{{ username }}"

- include_role:
    name: geerlingguy.ansible
  vars:
    ansible_install_method: pip
