---
- name: hostnamectl set-hostname
  shell: hostnamectl set-hostname {{ ansible_host }}
  when: ansible_host is defined

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    #validate: visuso -cf %s
  become: true
  become_user: root
    