- hosts: vms
  vars_prompt:
    - name: username
      prompt: "Enter user name"
      private: no
    - name: usermail
      prompt: "Enter user mail"
      private: no

  become: yes
  gather_facts: true

  roles:
  - host
  - proxy
  - packages
  - user
