---
- debug: 
    msg: Configuring proxy on host {{ ansible_host }}

- name: Update proxy in /etc/environment
  blockinfile:
    path: /etc/environment
    block: |
      http_proxy={{ proxy }}
      https_proxy={{ proxy }}
      ftp_proxy={{ proxy }}
      no_proxy={{ no_proxy }}
      HTTP_PROXY={{ proxy }}
      HTTPS_PROXY={{ proxy }}
      FTP_PROXY={{ proxy }}
      NO_PROXY={{ no_proxy }}
  
- name: Update proxy in /etc/yum.conf
  when: ansible_facts["distribution"] == "CentOS"
  lineinfile:
    path: /etc/yum.conf
    line: proxy={{ proxy }}

- name: Update proxy in /etc/apt/apt.conf
  when: ansible_facts["os_family"] == "Debian"
  blockinfile:
    path: /etc/apt/apt.conf.d/proxy.conf
    create: true
    block: |
      Acquire::http::Proxy "{{ proxy }}";
      Acquire::https::Proxy "{{ proxy }}";
      Acquire::ftp::Proxy "{{ proxy }}";

- name: Create ~/.docker directory
  file: path=/home/{{ username }}/.docker state=directory mode=0755

- name: Add proxy for docker containers
  template: src=dockerconfig.j2 dest=/home/{{ username }}/.docker/config.json owner={{ username }} group={{ username }} backup=yes